sass:
  style: :compressed  # Change to :expanded for debugging

permalink: /:year/:month/:day/:title.html

url: https://veithen.io

debug: false

disqus_categories:
  tech: 3550508
  opinion: 3550509
